spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: POSTGRESQL
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: test
    password: test
    driver-class-name: org.postgresql.Driver